name: Check Links

#on:
#  push:
#    branches: main
on: workflow_dispatch

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    environment:
      name: main
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Check links
      uses: byrnereese/github-action-mkdocs-link-check@main
      with:
        file-extension: '.md'
        verbose-mode: 'no'
        folder-path: 'docs'
        synchronous: 'yes'
        local-only: 'yes'
        recurse: 'yes'
        excludes: '(tel:|rcmobile:|https://marketplace.visualstudio.com|INSERT PERSON ID|INSERT TEAM ID|https://developer.ringcentral.com/new-app)'
